name: example
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.3.1

dependencies:
  linq: 1.0.0-dev.1
  sqlite3: ^2.4.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  build_runner: ^2.4.9
  linq_generator: ^1.0.0-dev.1
