name: linq
description: Operate the database using the Dart language without writing SQL.
version: 1.0.0-dev.1
repository: https://github.com/yiiim/linq
homepage: https://github.com/yiiim/linq


environment:
  sdk: ^3.0.0

dependencies:
  collection: ^1.18.0
  meta: ^1.7.0

dev_dependencies:
  sqlite3: ^2.4.3
  lints: ^3.0.0
  test: ^1.24.0
