name: linq
description: A starting point for Dart libraries or applications.
version: 1.0.0-dev.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0
# Add regular dependencies here.
dependencies:
  collection: any
  meta: ^1.7.0

dev_dependencies:
  sqlite3: ^2.4.3
  lints: ^3.0.0
  test: ^1.24.0
